name: Continuous Integration

on:
  push:
    branches:

  pull_request:
    branches:
    - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Install compilers and static analyzers
      if: matrix.os == 'ubuntu-24.04'
      run: >-
        sudo apt-get install cppcheck -y -q

        sudo update-alternatives --install
        /usr/bin/clang-tidy clang-tidy
        /usr/bin/clang-tidy-18 150

        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-18 150

    - name: Set up Spack
      uses: spack/setup-spack@v2
      with:
        ref: releases/v0.23
        color: true       # Force color output (SPACK_COLOR=always)
        path: spack

    - name: Choose environment
      run: |
        cp spack-repo/environments/hpxfft_ci.yaml spack.yaml
        cat spack-repo/environments/ci_env_settings.yaml.tpl >> spack.yaml
  
    - name: Concretize
      run: |
        spack -e . concretize

    - name: Install
      run: spack -e . install --no-check-signature

    - name: Configure
      env:
        CC: gcc-14
        CXX: g++-14
      run: |
        . /home/runner/work/HPX-FFT/HPX-FFT/spack/share/spack/setup-env.sh
        spack env activate .
        spack location -i hpx

    - name: Build/install HPX-FFT
      env:
        CC: gcc-14
        CXX: g++-14
      run: |
        . /home/runner/work/HPX-FFT/HPX-FFT/spack/share/spack/setup-env.sh
        spack env activate .
        rm -rf build
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/../install -DHPX_DIR=$(spack location -i hpx)
        make -j 2
        make install
        cd ..

    - name: Build Tests
      run: |
        . /home/runner/work/HPX-FFT/HPX-FFT/spack/share/spack/setup-env.sh
        spack env activate .
        rm -rf test/build
        mkdir test/build
        cd test/build
        cmake .. -DCMAKE_BUILD_TYPE=Release  -DHPXFFT_DIR=../install/lib/cmake/HPXFFT
        make -j 2
        cd ../..

    - name: Test sequential
      working-directory: test/build
      run: |
        export HPX_LOCALITIES=1
        ctest --output-on-failure --no-tests=ignore -j 2

    - name: Test parallel
      working-directory: test/build
      run: |
        export HPX_LOCALITIES=2
        ctest --output-on-failure --no-tests=ignore -j 2
      
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ matrix.os }}
        path: |
          prefix

    # See: https://github.com/spack/setup-spack?tab=readme-ov-file#example-caching-your-own-binaries-for-public-repositories
    - name: Push packages and update index
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: spack -e . buildcache push --base-image ubuntu:24.04 --update-index local-buildcache
      # The owner must match the namespace in /spack-repo/environments/ci_env_settings.yaml.tpl
      if: ${{ !cancelled() && github.repository_owner == 'constracktor' && github.event_name != 'pull_request' }}
